// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysviwpinggbgoolyanga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzdml3cGluZ2diZ29vbHlhbmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjM3NTAsImV4cCI6MjA2NTQ5OTc1MH0.XZhSwl4pwGLGfa6X_0UN9CcuCUw1aY1CvtT2IUXIXJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);